import Head from 'next/head';
import Posts from '../components/posts';
import { getAllPosts } from '../services/postService';

export default function Home({ posts }) {
  return (
    <div className='flex items-center justify-center'>
      <Head>
        <title>Bom Ajans</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div className='max-w-6xl'>
        <Posts posts={posts} />
      </div>
    </div>
  );
}

export async function getStaticProps() {
  const posts = await getAllPosts();
  return {
    props: {
      posts,
    },
    revalidate: 1800,
  };
}
